### ISSUE TITLE
Make sure people rename client plugin module to something else than 'clientPlugin'

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler-plugin-example#1]
People often are not aware of the fact that the name of the bpmn-js module matters (e.g. modules with same name will override others). If they create two plugins without renaming the module they'll wonder why only one of them works.

```javascript
module.exports = {
  __init__: [ 'clientPlugin' ],
  clientPlugin: [ 'type', ClientPlugin ] // must be renamed
};
```

**Comment by nikku** [comment]
Will be fixed with an additional note in the `README` as well as source code.

The name of the service will be `PLEASE_RENAME_ME`.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler-plugin-example/commit/87470b0c0aba73421fae42833efca97bf6322357.
