### ISSUE TITLE
Update for Camunda Modeler 4.0+?

### ISSUE THREAD

**Issue by sgoodrow-zymergen** [camunda/camunda-modeler-plugin-example#3]
We have written several plugins for 3.x, but are looking to upgrade our base modeler that we ship the plugins with. The 4.x upgrade bumped the version of electron significantly and seems to have changed the requirements for plugin development.

Would it be possible to upgrade this plugin example to work with 4.x?

**Comment by pinussilvestrus** [comment]
Thanks for reaching out! Can you use our [issue templates](https://github.com/camunda/camunda-modeler-plugin-example/issues/new/choose) to provide the necessary information? Note: they were missed in this project, I just added them.

> and seems to have changed the requirements for plugin development.

Can you give more details about this? What did change in particular regarding this example plugin?

**Comment by nikku** [comment]
Closing this issue.

Please use our existing issue template. If you quote examples, please link them.

**Comment by nikku** [comment]
I did a quick check to verify this example works fine with Camunda Modeler v4.10.
